# Generated by Django 3.2.4 on 2021-06-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_note_my_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='my_notes',
            new_name='profile',
        ),
    ]
