# Generated by Django 3.2.4 on 2021-06-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0003_rename_my_notes_note_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='notes_app.profile'),
        ),
    ]
